name: BergeyPvp
version: 0.1
author: valadian
main: com.valadian.bergecraft.BergeyPvp
depends: [NameLayer]
dev-url: null
commands:
  bergeypvp:
    description: Gets and sets BergeyPvp settings
    usage: /bergeypvp <setting> [<value>]
    permission: bergeypvp.console
permissions:
  bergeypvp.console:
    description: Console commands for Bergecraft
    default: false